# Generated by Django 4.1.1 on 2022-12-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_label_user_alter_todo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='image',
            field=models.FileField(null=True, upload_to='to_do'),
        ),
    ]
