# Generated by Django 4.1.1 on 2022-12-16 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_alter_todo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='label',
            name='label_title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
