# Generated by Django 4.1.1 on 2022-12-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_label_slug_alter_label_label_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='task_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
