# Generated by Django 4.1.1 on 2022-12-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_todo_completed_todo_task_id_alter_todo_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
